/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* cells_not_processed =  1  *)
(* src = "trojan1.v:1.1-19.10" *)
module Trojan1(clk, rst, r1, trigger);
  reg \$auto$verilog_backend.cc:2184:dump_module$293  = 0;
  (* src = "trojan1.v:10.2-16.6" *)
  reg [3:0] _00_;
  (* src = "trojan1.v:10.2-16.6" *)
  reg [3:0] _01_;
  (* src = "trojan1.v:10.2-16.6" *)
  reg [3:0] _02_;
  wire [3:0] _03_;
  wire _04_;
  wire [3:0] _05_;
  (* src = "trojan1.v:15.27-15.41" *)
  wire [3:0] _06_;
  wire _07_;
  wire _08_;
  wire [15:0] _09_;
  wire [7:0] _10_;
  wire [3:0] _11_;
  wire [1:0] _12_;
  wire _13_;
  wire [31:0] _14_;
  wire _15_;
  (* src = "trojan1.v:15.8-15.15" *)
  wire _16_;
  (* src = "trojan1.v:12.8-12.12" *)
  wire _17_;
  (* force_downto = 32'd1 *)
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:266.22-266.23" *)
  wire _18_;
  (* force_downto = 32'd1 *)
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:277.21-277.23" *)
  wire [3:0] _19_;
  (* force_downto = 32'd1 *)
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:282.21-282.26" *)
  wire [3:0] _20_;
  (* force_downto = 32'd1 *)
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire [3:0] _21_;
  (* force_downto = 32'd1 *)
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [3:0] _22_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:272.12-272.14" *)
  wire _23_;
  (* force_downto = 32'd1 *)
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:282.28-282.33" *)
  wire [3:0] _24_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:272.8-272.10" *)
  wire _25_;
  (* force_downto = 32'd1 *)
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [3:0] _26_;
  (* force_downto = 32'd1 *)
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _27_;
  (* force_downto = 32'd1 *)
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _28_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:215.8-215.10" *)
  wire _29_;
  (* force_downto = 32'd1 *)
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:218.21-218.23" *)
  wire [3:0] _30_;
  (* force_downto = 32'd1 *)
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [3:0] _31_;
  (* force_downto = 32'd1 *)
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.20-214.21" *)
  wire [3:0] _32_;
  wire [1023:0] _33_;
  (* force_downto = 32'd1 *)
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:222.21-222.22" *)
  wire [3:0] _34_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:220.10-220.11" *)
  wire [31:0] _35_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:220.13-220.14" *)
  wire [31:0] _36_;
  (* force_downto = 32'd1 *)
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:222.18-222.19" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] _37_;
  wire [3:0] _38_;
  wire [3:0] _39_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)
  wire [3:0] _40_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *)
  wire [3:0] _41_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:279.26-279.45" *)
  wire [3:0] _42_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)
  wire [3:0] _43_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)
  wire [4:0] _44_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:231.18-231.27" *)
  wire _45_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _46_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _47_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _48_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _49_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _50_;
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _51_;
  (* src = "trojan1.v:2.8-2.11" *)
  input clk;
  wire clk;
  (* src = "trojan1.v:8.13-8.20" *)
  reg [3:0] counter;
  (* src = "trojan1.v:4.8-4.10" *)
  input r1;
  wire r1;
  (* src = "trojan1.v:3.8-3.11" *)
  input rst;
  wire rst;
  (* src = "trojan1.v:5.9-5.16" *)
  output trigger;
  wire trigger;
  \$_NOT_  _52_ (
    .A(r1),
    .Y(_07_)
  );
  \$_NOT_  _53_ (
    .A(_01_[0]),
    .Y(_08_)
  );
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _54_ (
    .A(_24_[1]),
    .Y(_41_[1])
  );
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _55_ (
    .A(_24_[2]),
    .Y(_41_[2])
  );
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _56_ (
    .A(_24_[3]),
    .Y(_41_[3])
  );
  (* src = "trojan1.v:12.8-12.12" *)
  \$_NOT_  _57_ (
    .A(rst),
    .Y(_17_)
  );
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _58_ (
    .A(_38_[1]),
    .B(_39_[0]),
    .Y(_44_[1])
  );
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _59_ (
    .A(_38_[2]),
    .B(_39_[1]),
    .Y(_44_[2])
  );
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _60_ (
    .A(_38_[3]),
    .B(_39_[2]),
    .Y(_44_[3])
  );
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _61_ (
    .A(_38_[1]),
    .B(_39_[0]),
    .Y(_46_)
  );
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _62_ (
    .A(_49_),
    .B(_39_[1]),
    .Y(_48_)
  );
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _63_ (
    .A(_38_[3]),
    .B(_38_[2]),
    .Y(_49_)
  );
  (* src = "trojan1.v:15.27-15.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _64_ (
    .A(_38_[2]),
    .B(_39_[1]),
    .Y(_50_)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$293 ) begin end
    _00_ = _02_;
    (* src = "trojan1.v:12.4-14.7" *)
    casez (_17_)
      /* src = "trojan1.v:12.8-12.12" */
      1'h1:
          _01_ = 4'h0;
      default:
          _01_ = counter;
    endcase
    (* src = "trojan1.v:15.4-15.42" *)
    casez (_16_)
      /* src = "trojan1.v:15.8-15.15" */
      1'h1:
          _02_ = _06_;
      default:
          _02_ = _01_;
    endcase
  end
  always @(posedge clk) begin
      counter <= _00_;
  end
  assign trigger = counter[3];
  assign _26_ = _39_;
  assign _27_ = _38_;
  assign _28_ = _06_;
  assign _21_ = _01_;
  assign _18_ = 1'h1;
  assign _19_ = _20_;
  assign _22_ = _42_;
  assign _38_ = _43_;
  assign _06_ = _44_[3:0];
  assign _30_ = _39_;
  assign _31_ = _40_;
  assign _32_ = _38_;
  assign _33_ = 1024'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070726f633b206f7074202d66617374;
  assign _34_ = _39_;
  assign _37_[0] = _38_[0];
  assign _36_ = 32'd4;
  assign _35_ = 32'd0;
  assign _24_ = _01_;
  assign _20_ = 4'h1;
  assign _14_[0] = _07_;
  assign _14_[1] = 1'h0;
  assign _14_[2] = 1'h0;
  assign _14_[3] = 1'h0;
  assign _14_[4] = 1'h0;
  assign _14_[5] = 1'h0;
  assign _14_[6] = 1'h0;
  assign _14_[7] = 1'h0;
  assign _14_[8] = 1'h0;
  assign _14_[9] = 1'h0;
  assign _14_[10] = 1'h0;
  assign _14_[11] = 1'h0;
  assign _14_[12] = 1'h0;
  assign _14_[13] = 1'h0;
  assign _14_[14] = 1'h0;
  assign _14_[15] = 1'h0;
  assign _14_[16] = 1'h0;
  assign _14_[17] = 1'h0;
  assign _14_[18] = 1'h0;
  assign _14_[19] = 1'h0;
  assign _14_[20] = 1'h0;
  assign _14_[21] = 1'h0;
  assign _14_[22] = 1'h0;
  assign _14_[23] = 1'h0;
  assign _14_[24] = 1'h0;
  assign _14_[25] = 1'h0;
  assign _14_[26] = 1'h0;
  assign _14_[27] = 1'h0;
  assign _14_[28] = 1'h0;
  assign _14_[29] = 1'h0;
  assign _14_[30] = 1'h0;
  assign _14_[31] = 1'h0;
  assign _09_[0] = _07_;
  assign _09_[1] = 1'h0;
  assign _09_[2] = 1'h0;
  assign _09_[3] = 1'h0;
  assign _09_[4] = 1'h0;
  assign _09_[5] = 1'h0;
  assign _09_[6] = 1'h0;
  assign _09_[7] = 1'h0;
  assign _09_[8] = 1'h0;
  assign _09_[9] = 1'h0;
  assign _09_[10] = 1'h0;
  assign _09_[11] = 1'h0;
  assign _09_[12] = 1'h0;
  assign _09_[13] = 1'h0;
  assign _09_[14] = 1'h0;
  assign _09_[15] = 1'h0;
  assign _10_[0] = _07_;
  assign _10_[1] = 1'h0;
  assign _10_[2] = 1'h0;
  assign _10_[3] = 1'h0;
  assign _10_[4] = 1'h0;
  assign _10_[5] = 1'h0;
  assign _10_[6] = 1'h0;
  assign _10_[7] = 1'h0;
  assign _11_[0] = _07_;
  assign _11_[1] = 1'h0;
  assign _11_[2] = 1'h0;
  assign _11_[3] = 1'h0;
  assign _12_[0] = _07_;
  assign _12_[1] = 1'h0;
  assign _15_ = _07_;
  assign _42_[3] = _01_[3];
  assign _43_[3] = _01_[3];
  assign _42_[2] = _01_[2];
  assign _43_[2] = _01_[2];
  assign _42_[1] = _01_[1];
  assign _43_[1] = _01_[1];
  assign _40_[1] = 1'h0;
  assign _42_[0] = _01_[0];
  assign _40_[0] = _01_[0];
  assign _43_[0] = _08_;
  assign _45_ = 1'h0;
  assign _39_[0] = _01_[0];
  assign _39_[1] = _46_;
  assign _40_[3] = 1'h0;
  assign _40_[2] = 1'h0;
  assign _47_ = 1'h0;
  assign _51_ = 1'h0;
  assign _39_[3] = _48_;
  assign _44_[4] = _48_;
  assign _39_[2] = _50_;
  assign _44_[0] = _08_;
  assign _16_ = r1;
  assign _41_[0] = _08_;
endmodule
