/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "entrada/trojan2.v:1.1-21.10" *)
module Trojan2(clk, rst, data_in, force_reset);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "entrada/trojan2.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "entrada/trojan2.v:4.22-4.29" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "entrada/trojan2.v:5.16-5.27" *)
  output force_reset;
  wire force_reset;
  (* src = "entrada/trojan2.v:7.15-7.24" *)
  wire [7:0] prev_data;
  (* src = "entrada/trojan2.v:3.16-3.19" *)
  input rst;
  wire rst;
  (* src = "entrada/trojan2.v:8.10-8.17" *)
  wire trigger;
  \$_ANDNOT_  _14_ (
    .A(prev_data[1]),
    .B(prev_data[0]),
    .Y(_00_)
  );
  \$_ORNOT_  _15_ (
    .A(prev_data[2]),
    .B(prev_data[3]),
    .Y(_01_)
  );
  \$_ANDNOT_  _16_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  \$_ORNOT_  _17_ (
    .A(prev_data[4]),
    .B(prev_data[5]),
    .Y(_03_)
  );
  \$_ORNOT_  _18_ (
    .A(prev_data[6]),
    .B(prev_data[7]),
    .Y(_04_)
  );
  \$_OR_  _19_ (
    .A(_04_),
    .B(_03_),
    .Y(_05_)
  );
  \$_ANDNOT_  _20_ (
    .A(_02_),
    .B(_05_),
    .Y(_06_)
  );
  \$_ORNOT_  _21_ (
    .A(data_in[1]),
    .B(data_in[0]),
    .Y(_07_)
  );
  \$_ORNOT_  _22_ (
    .A(data_in[3]),
    .B(data_in[2]),
    .Y(_08_)
  );
  \$_OR_  _23_ (
    .A(_08_),
    .B(_07_),
    .Y(_09_)
  );
  \$_ORNOT_  _24_ (
    .A(data_in[5]),
    .B(data_in[4]),
    .Y(_10_)
  );
  \$_ORNOT_  _25_ (
    .A(data_in[7]),
    .B(data_in[6]),
    .Y(_11_)
  );
  \$_OR_  _26_ (
    .A(_11_),
    .B(_10_),
    .Y(_12_)
  );
  \$_OR_  _27_ (
    .A(_12_),
    .B(_09_),
    .Y(_13_)
  );
  \$_ANDNOT_  _28_ (
    .A(_06_),
    .B(_13_),
    .Y(trigger)
  );
  (* src = "entrada/trojan2.v:15.5-20.8" *)
  dff _29_ (
    .CK(clk),
    .D(trigger),
    .Q(force_reset),
    .RN(rst),
    .SN(1'h1)
  );
  (* src = "entrada/trojan2.v:9.5-14.8" *)
  dff _30_ (
    .CK(clk),
    .D(data_in[0]),
    .Q(prev_data[0]),
    .RN(rst),
    .SN(1'h1)
  );
  (* src = "entrada/trojan2.v:9.5-14.8" *)
  dff _31_ (
    .CK(clk),
    .D(data_in[1]),
    .Q(prev_data[1]),
    .RN(rst),
    .SN(1'h1)
  );
  (* src = "entrada/trojan2.v:9.5-14.8" *)
  dff _32_ (
    .CK(clk),
    .D(data_in[2]),
    .Q(prev_data[2]),
    .RN(rst),
    .SN(1'h1)
  );
  (* src = "entrada/trojan2.v:9.5-14.8" *)
  dff _33_ (
    .CK(clk),
    .D(data_in[3]),
    .Q(prev_data[3]),
    .RN(rst),
    .SN(1'h1)
  );
  (* src = "entrada/trojan2.v:9.5-14.8" *)
  dff _34_ (
    .CK(clk),
    .D(data_in[4]),
    .Q(prev_data[4]),
    .RN(rst),
    .SN(1'h1)
  );
  (* src = "entrada/trojan2.v:9.5-14.8" *)
  dff _35_ (
    .CK(clk),
    .D(data_in[5]),
    .Q(prev_data[5]),
    .RN(rst),
    .SN(1'h1)
  );
  (* src = "entrada/trojan2.v:9.5-14.8" *)
  dff _36_ (
    .CK(clk),
    .D(data_in[6]),
    .Q(prev_data[6]),
    .RN(rst),
    .SN(1'h1)
  );
  (* src = "entrada/trojan2.v:9.5-14.8" *)
  dff _37_ (
    .CK(clk),
    .D(data_in[7]),
    .Q(prev_data[7]),
    .RN(rst),
    .SN(1'h1)
  );
endmodule
