/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "entrada/trojan7.v:1.1-16.10" *)
module Trojan7(wb_addr_i, wb_data_i, s0_data_i, slv_sel);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  (* src = "entrada/trojan7.v:4.18-4.27" *)
  input [31:0] s0_data_i;
  wire [31:0] s0_data_i;
  (* src = "entrada/trojan7.v:5.22-5.29" *)
  output [3:0] slv_sel;
  wire [3:0] slv_sel;
  (* src = "entrada/trojan7.v:2.18-2.27" *)
  input [31:0] wb_addr_i;
  wire [31:0] wb_addr_i;
  (* src = "entrada/trojan7.v:3.18-3.27" *)
  input [31:0] wb_data_i;
  wire [31:0] wb_data_i;
  \$_NOR_  _063_ (
    .A(wb_data_i[1]),
    .B(wb_data_i[0]),
    .Y(_036_)
  );
  \$_OR_  _064_ (
    .A(wb_data_i[3]),
    .B(wb_data_i[2]),
    .Y(_037_)
  );
  \$_ANDNOT_  _065_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  \$_ORNOT_  _066_ (
    .A(wb_data_i[4]),
    .B(wb_data_i[5]),
    .Y(_039_)
  );
  \$_NAND_  _067_ (
    .A(wb_data_i[7]),
    .B(wb_data_i[6]),
    .Y(_040_)
  );
  \$_OR_  _068_ (
    .A(_040_),
    .B(_039_),
    .Y(_041_)
  );
  \$_ANDNOT_  _069_ (
    .A(_038_),
    .B(_041_),
    .Y(_042_)
  );
  \$_OR_  _070_ (
    .A(wb_data_i[9]),
    .B(wb_data_i[8]),
    .Y(_043_)
  );
  \$_NAND_  _071_ (
    .A(wb_data_i[11]),
    .B(wb_data_i[10]),
    .Y(_044_)
  );
  \$_OR_  _072_ (
    .A(_044_),
    .B(_043_),
    .Y(_045_)
  );
  \$_NAND_  _073_ (
    .A(wb_data_i[13]),
    .B(wb_data_i[12]),
    .Y(_046_)
  );
  \$_ORNOT_  _074_ (
    .A(wb_data_i[14]),
    .B(wb_data_i[15]),
    .Y(_047_)
  );
  \$_OR_  _075_ (
    .A(_047_),
    .B(_046_),
    .Y(_048_)
  );
  \$_OR_  _076_ (
    .A(_048_),
    .B(_045_),
    .Y(_049_)
  );
  \$_ANDNOT_  _077_ (
    .A(_042_),
    .B(_049_),
    .Y(_050_)
  );
  \$_ORNOT_  _078_ (
    .A(wb_data_i[16]),
    .B(wb_data_i[17]),
    .Y(_051_)
  );
  \$_ORNOT_  _079_ (
    .A(wb_data_i[18]),
    .B(wb_data_i[19]),
    .Y(_052_)
  );
  \$_OR_  _080_ (
    .A(_052_),
    .B(_051_),
    .Y(_053_)
  );
  \$_NAND_  _081_ (
    .A(wb_data_i[21]),
    .B(wb_data_i[20]),
    .Y(_054_)
  );
  \$_NAND_  _082_ (
    .A(wb_data_i[23]),
    .B(wb_data_i[22]),
    .Y(_055_)
  );
  \$_OR_  _083_ (
    .A(_055_),
    .B(_054_),
    .Y(_056_)
  );
  \$_OR_  _084_ (
    .A(_056_),
    .B(_053_),
    .Y(_057_)
  );
  \$_ORNOT_  _085_ (
    .A(wb_data_i[24]),
    .B(wb_data_i[25]),
    .Y(_058_)
  );
  \$_ORNOT_  _086_ (
    .A(wb_data_i[26]),
    .B(wb_data_i[27]),
    .Y(_059_)
  );
  \$_OR_  _087_ (
    .A(_059_),
    .B(_058_),
    .Y(_060_)
  );
  \$_ORNOT_  _088_ (
    .A(wb_data_i[28]),
    .B(wb_data_i[29]),
    .Y(_061_)
  );
  \$_OR_  _089_ (
    .A(wb_data_i[31]),
    .B(wb_data_i[30]),
    .Y(_062_)
  );
  \$_OR_  _090_ (
    .A(_062_),
    .B(_061_),
    .Y(_000_)
  );
  \$_OR_  _091_ (
    .A(_000_),
    .B(_060_),
    .Y(_001_)
  );
  \$_OR_  _092_ (
    .A(_001_),
    .B(_057_),
    .Y(_002_)
  );
  \$_ANDNOT_  _093_ (
    .A(_050_),
    .B(_002_),
    .Y(_003_)
  );
  \$_OR_  _094_ (
    .A(s0_data_i[1]),
    .B(s0_data_i[0]),
    .Y(_004_)
  );
  \$_NAND_  _095_ (
    .A(s0_data_i[3]),
    .B(s0_data_i[2]),
    .Y(_005_)
  );
  \$_OR_  _096_ (
    .A(_005_),
    .B(_004_),
    .Y(_006_)
  );
  \$_ORNOT_  _097_ (
    .A(s0_data_i[4]),
    .B(s0_data_i[5]),
    .Y(_007_)
  );
  \$_ORNOT_  _098_ (
    .A(s0_data_i[6]),
    .B(s0_data_i[7]),
    .Y(_008_)
  );
  \$_OR_  _099_ (
    .A(_008_),
    .B(_007_),
    .Y(_009_)
  );
  \$_OR_  _100_ (
    .A(_009_),
    .B(_006_),
    .Y(_010_)
  );
  \$_ORNOT_  _101_ (
    .A(s0_data_i[8]),
    .B(s0_data_i[9]),
    .Y(_011_)
  );
  \$_OR_  _102_ (
    .A(s0_data_i[11]),
    .B(s0_data_i[10]),
    .Y(_012_)
  );
  \$_OR_  _103_ (
    .A(_012_),
    .B(_011_),
    .Y(_013_)
  );
  \$_ORNOT_  _104_ (
    .A(s0_data_i[13]),
    .B(s0_data_i[12]),
    .Y(_014_)
  );
  \$_ORNOT_  _105_ (
    .A(s0_data_i[15]),
    .B(s0_data_i[14]),
    .Y(_015_)
  );
  \$_OR_  _106_ (
    .A(_015_),
    .B(_014_),
    .Y(_016_)
  );
  \$_OR_  _107_ (
    .A(_016_),
    .B(_013_),
    .Y(_017_)
  );
  \$_OR_  _108_ (
    .A(_017_),
    .B(_010_),
    .Y(_018_)
  );
  \$_ORNOT_  _109_ (
    .A(s0_data_i[17]),
    .B(s0_data_i[16]),
    .Y(_019_)
  );
  \$_ORNOT_  _110_ (
    .A(s0_data_i[19]),
    .B(s0_data_i[18]),
    .Y(_020_)
  );
  \$_OR_  _111_ (
    .A(_020_),
    .B(_019_),
    .Y(_021_)
  );
  \$_ORNOT_  _112_ (
    .A(s0_data_i[21]),
    .B(s0_data_i[20]),
    .Y(_022_)
  );
  \$_ORNOT_  _113_ (
    .A(s0_data_i[23]),
    .B(s0_data_i[22]),
    .Y(_023_)
  );
  \$_OR_  _114_ (
    .A(_023_),
    .B(_022_),
    .Y(_024_)
  );
  \$_OR_  _115_ (
    .A(_024_),
    .B(_021_),
    .Y(_025_)
  );
  \$_ORNOT_  _116_ (
    .A(s0_data_i[24]),
    .B(s0_data_i[25]),
    .Y(_026_)
  );
  \$_NAND_  _117_ (
    .A(s0_data_i[27]),
    .B(s0_data_i[26]),
    .Y(_027_)
  );
  \$_OR_  _118_ (
    .A(_027_),
    .B(_026_),
    .Y(_028_)
  );
  \$_ORNOT_  _119_ (
    .A(s0_data_i[29]),
    .B(s0_data_i[28]),
    .Y(_029_)
  );
  \$_OR_  _120_ (
    .A(s0_data_i[31]),
    .B(s0_data_i[30]),
    .Y(_030_)
  );
  \$_OR_  _121_ (
    .A(_030_),
    .B(_029_),
    .Y(_031_)
  );
  \$_OR_  _122_ (
    .A(_031_),
    .B(_028_),
    .Y(_032_)
  );
  \$_OR_  _123_ (
    .A(_032_),
    .B(_025_),
    .Y(_033_)
  );
  \$_OR_  _124_ (
    .A(_033_),
    .B(_018_),
    .Y(_034_)
  );
  \$_ANDNOT_  _125_ (
    .A(_003_),
    .B(_034_),
    .Y(_035_)
  );
  \$_XOR_  _126_ (
    .A(_035_),
    .B(wb_addr_i[28]),
    .Y(slv_sel[0])
  );
  \$_XOR_  _127_ (
    .A(_035_),
    .B(wb_addr_i[29]),
    .Y(slv_sel[1])
  );
  \$_XOR_  _128_ (
    .A(_035_),
    .B(wb_addr_i[30]),
    .Y(slv_sel[2])
  );
  \$_XOR_  _129_ (
    .A(_035_),
    .B(wb_addr_i[31]),
    .Y(slv_sel[3])
  );
endmodule
