/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "entrada/trojan1.v:1.1-19.10" *)
module Trojan1(clk, rst, r1, trigger);
  (* src = "entrada/trojan1.v:10.2-16.6" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "entrada/trojan1.v:2.8-2.11" *)
  input clk;
  wire clk;
  (* src = "entrada/trojan1.v:8.13-8.20" *)
  wire [3:0] counter;
  (* src = "entrada/trojan1.v:4.8-4.10" *)
  input r1;
  wire r1;
  (* src = "entrada/trojan1.v:3.8-3.11" *)
  input rst;
  wire rst;
  (* src = "entrada/trojan1.v:5.9-5.16" *)
  output trigger;
  wire trigger;
  \$_AND_  _10_ (
    .A(rst),
    .B(counter[0]),
    .Y(_01_)
  );
  \$_XOR_  _11_ (
    .A(_01_),
    .B(r1),
    .Y(_00_[0])
  );
  \$_AND_  _12_ (
    .A(counter[1]),
    .B(rst),
    .Y(_02_)
  );
  \$_XOR_  _13_ (
    .A(_02_),
    .B(_01_),
    .Y(_03_)
  );
  \$_MUX_  _14_ (
    .A(_02_),
    .B(_03_),
    .S(r1),
    .Y(_00_[1])
  );
  \$_AND_  _15_ (
    .A(counter[2]),
    .B(rst),
    .Y(_04_)
  );
  \$_NAND_  _16_ (
    .A(_02_),
    .B(_01_),
    .Y(_05_)
  );
  \$_XNOR_  _17_ (
    .A(_05_),
    .B(_04_),
    .Y(_06_)
  );
  \$_MUX_  _18_ (
    .A(_04_),
    .B(_06_),
    .S(r1),
    .Y(_00_[2])
  );
  \$_AND_  _19_ (
    .A(counter[3]),
    .B(rst),
    .Y(_07_)
  );
  \$_ANDNOT_  _20_ (
    .A(_04_),
    .B(_05_),
    .Y(_08_)
  );
  \$_XOR_  _21_ (
    .A(_08_),
    .B(_07_),
    .Y(_09_)
  );
  \$_MUX_  _22_ (
    .A(_07_),
    .B(_09_),
    .S(r1),
    .Y(_00_[3])
  );
  (* src = "entrada/trojan1.v:10.2-16.6" *)
  dff _23_ (
    .CK(clk),
    .D(_00_[0]),
    .Q(counter[0]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan1.v:10.2-16.6" *)
  dff _24_ (
    .CK(clk),
    .D(_00_[1]),
    .Q(counter[1]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan1.v:10.2-16.6" *)
  dff _25_ (
    .CK(clk),
    .D(_00_[2]),
    .Q(counter[2]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan1.v:10.2-16.6" *)
  dff _26_ (
    .CK(clk),
    .D(_00_[3]),
    .Q(counter[3]),
    .RN(1'h0),
    .SN(1'h1)
  );
  assign trigger = counter[3];
endmodule
