/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "entrada/trojan0.v:1.1-16.10" *)
module Trojan0(clk, rst, key, load);
  (* src = "entrada/trojan0.v:10.2-14.5" *)
  wire [63:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  (* src = "entrada/trojan0.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "entrada/trojan0.v:7.14-7.21" *)
  wire [19:0] counter;
  (* src = "entrada/trojan0.v:4.24-4.27" *)
  input [127:0] key;
  wire [127:0] key;
  (* hdlname = "lfsr clk" *)
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:20.13-20.16" *)
  wire \lfsr.clk ;
  (* hdlname = "lfsr lfsr" *)
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:21.16-21.20" *)
  wire [19:0] \lfsr.lfsr ;
  (* hdlname = "lfsr lfsr_stream" *)
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:24.13-24.24" *)
  wire [19:0] \lfsr.lfsr_stream ;
  (* hdlname = "lfsr rst" *)
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:20.8-20.11" *)
  wire \lfsr.rst ;
  (* src = "entrada/trojan0.v:5.23-5.27" *)
  output [63:0] load;
  wire [63:0] load;
  (* src = "entrada/trojan0.v:3.16-3.19" *)
  input rst;
  wire rst;
  \$_NOT_  _25_ (
    .A(rst),
    .Y(_21_)
  );
  \$_XOR_  _26_ (
    .A(\lfsr.lfsr_stream [0]),
    .B(key[0]),
    .Y(_00_[7])
  );
  \$_XOR_  _27_ (
    .A(\lfsr.lfsr_stream [1]),
    .B(key[1]),
    .Y(_00_[15])
  );
  \$_XOR_  _28_ (
    .A(\lfsr.lfsr_stream [2]),
    .B(key[2]),
    .Y(_00_[23])
  );
  \$_XOR_  _29_ (
    .A(\lfsr.lfsr_stream [3]),
    .B(key[3]),
    .Y(_00_[31])
  );
  \$_XOR_  _30_ (
    .A(\lfsr.lfsr_stream [4]),
    .B(key[4]),
    .Y(_00_[39])
  );
  \$_XOR_  _31_ (
    .A(\lfsr.lfsr_stream [5]),
    .B(key[5]),
    .Y(_00_[47])
  );
  \$_XOR_  _32_ (
    .A(\lfsr.lfsr_stream [6]),
    .B(key[6]),
    .Y(_00_[55])
  );
  \$_XOR_  _33_ (
    .A(\lfsr.lfsr_stream [7]),
    .B(key[7]),
    .Y(_00_[63])
  );
  \$_OR_  _34_ (
    .A(\lfsr.lfsr_stream [1]),
    .B(rst),
    .Y(_01_)
  );
  \$_AND_  _35_ (
    .A(\lfsr.lfsr_stream [2]),
    .B(_21_),
    .Y(_02_)
  );
  \$_AND_  _36_ (
    .A(\lfsr.lfsr_stream [3]),
    .B(_21_),
    .Y(_03_)
  );
  \$_AND_  _37_ (
    .A(\lfsr.lfsr_stream [4]),
    .B(_21_),
    .Y(_04_)
  );
  \$_OR_  _38_ (
    .A(\lfsr.lfsr_stream [5]),
    .B(rst),
    .Y(_05_)
  );
  \$_OR_  _39_ (
    .A(\lfsr.lfsr_stream [6]),
    .B(rst),
    .Y(_06_)
  );
  \$_AND_  _40_ (
    .A(\lfsr.lfsr_stream [7]),
    .B(_21_),
    .Y(_07_)
  );
  \$_AND_  _41_ (
    .A(_21_),
    .B(\lfsr.lfsr_stream [8]),
    .Y(_08_)
  );
  \$_AND_  _42_ (
    .A(_21_),
    .B(\lfsr.lfsr_stream [9]),
    .Y(_09_)
  );
  \$_AND_  _43_ (
    .A(_21_),
    .B(\lfsr.lfsr_stream [10]),
    .Y(_10_)
  );
  \$_AND_  _44_ (
    .A(\lfsr.lfsr_stream [11]),
    .B(_21_),
    .Y(_11_)
  );
  \$_AND_  _45_ (
    .A(_21_),
    .B(\lfsr.lfsr_stream [12]),
    .Y(_12_)
  );
  \$_OR_  _46_ (
    .A(rst),
    .B(\lfsr.lfsr_stream [13]),
    .Y(_13_)
  );
  \$_OR_  _47_ (
    .A(rst),
    .B(\lfsr.lfsr_stream [14]),
    .Y(_14_)
  );
  \$_AND_  _48_ (
    .A(\lfsr.lfsr_stream [15]),
    .B(_21_),
    .Y(_15_)
  );
  \$_AND_  _49_ (
    .A(_21_),
    .B(\lfsr.lfsr_stream [16]),
    .Y(_16_)
  );
  \$_AND_  _50_ (
    .A(_21_),
    .B(\lfsr.lfsr_stream [17]),
    .Y(_17_)
  );
  \$_AND_  _51_ (
    .A(_21_),
    .B(\lfsr.lfsr_stream [18]),
    .Y(_18_)
  );
  \$_AND_  _52_ (
    .A(_21_),
    .B(\lfsr.lfsr_stream [19]),
    .Y(_19_)
  );
  \$_XOR_  _53_ (
    .A(\lfsr.lfsr_stream [11]),
    .B(\lfsr.lfsr_stream [15]),
    .Y(_22_)
  );
  \$_XNOR_  _54_ (
    .A(\lfsr.lfsr_stream [7]),
    .B(_22_),
    .Y(_23_)
  );
  \$_XNOR_  _55_ (
    .A(\lfsr.lfsr_stream [0]),
    .B(_23_),
    .Y(_24_)
  );
  \$_AND_  _56_ (
    .A(_21_),
    .B(_24_),
    .Y(_20_)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _57_ (
    .CK(clk),
    .D(_01_),
    .Q(\lfsr.lfsr_stream [0]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _58_ (
    .CK(clk),
    .D(_02_),
    .Q(\lfsr.lfsr_stream [1]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _59_ (
    .CK(clk),
    .D(_03_),
    .Q(\lfsr.lfsr_stream [2]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _60_ (
    .CK(clk),
    .D(_04_),
    .Q(\lfsr.lfsr_stream [3]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _61_ (
    .CK(clk),
    .D(_05_),
    .Q(\lfsr.lfsr_stream [4]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _62_ (
    .CK(clk),
    .D(_06_),
    .Q(\lfsr.lfsr_stream [5]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _63_ (
    .CK(clk),
    .D(_07_),
    .Q(\lfsr.lfsr_stream [6]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _64_ (
    .CK(clk),
    .D(_08_),
    .Q(\lfsr.lfsr_stream [7]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _65_ (
    .CK(clk),
    .D(_09_),
    .Q(\lfsr.lfsr_stream [8]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _66_ (
    .CK(clk),
    .D(_10_),
    .Q(\lfsr.lfsr_stream [9]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _67_ (
    .CK(clk),
    .D(_11_),
    .Q(\lfsr.lfsr_stream [10]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _68_ (
    .CK(clk),
    .D(_12_),
    .Q(\lfsr.lfsr_stream [11]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _69_ (
    .CK(clk),
    .D(_13_),
    .Q(\lfsr.lfsr_stream [12]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _70_ (
    .CK(clk),
    .D(_14_),
    .Q(\lfsr.lfsr_stream [13]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _71_ (
    .CK(clk),
    .D(_15_),
    .Q(\lfsr.lfsr_stream [14]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _72_ (
    .CK(clk),
    .D(_16_),
    .Q(\lfsr.lfsr_stream [15]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _73_ (
    .CK(clk),
    .D(_17_),
    .Q(\lfsr.lfsr_stream [16]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _74_ (
    .CK(clk),
    .D(_18_),
    .Q(\lfsr.lfsr_stream [17]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _75_ (
    .CK(clk),
    .D(_19_),
    .Q(\lfsr.lfsr_stream [18]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:8.15-8.39|entrada/trojan0.v:31.2-36.6" *)
  dff _76_ (
    .CK(clk),
    .D(_20_),
    .Q(\lfsr.lfsr_stream [19]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:10.2-14.5" *)
  dff _77_ (
    .CK(clk),
    .D(_00_[7]),
    .Q(load[7]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:10.2-14.5" *)
  dff _78_ (
    .CK(clk),
    .D(_00_[15]),
    .Q(load[15]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:10.2-14.5" *)
  dff _79_ (
    .CK(clk),
    .D(_00_[23]),
    .Q(load[23]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:10.2-14.5" *)
  dff _80_ (
    .CK(clk),
    .D(_00_[31]),
    .Q(load[31]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:10.2-14.5" *)
  dff _81_ (
    .CK(clk),
    .D(_00_[39]),
    .Q(load[39]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:10.2-14.5" *)
  dff _82_ (
    .CK(clk),
    .D(_00_[47]),
    .Q(load[47]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:10.2-14.5" *)
  dff _83_ (
    .CK(clk),
    .D(_00_[55]),
    .Q(load[55]),
    .RN(1'h0),
    .SN(1'h1)
  );
  (* src = "entrada/trojan0.v:10.2-14.5" *)
  dff _84_ (
    .CK(clk),
    .D(_00_[63]),
    .Q(load[56]),
    .RN(1'h0),
    .SN(1'h1)
  );
  assign { _00_[62:56], _00_[54:48], _00_[46:40], _00_[38:32], _00_[30:24], _00_[22:16], _00_[14:8], _00_[6:0] } = { _00_[63], _00_[63], _00_[63], _00_[63], _00_[63], _00_[63], _00_[63], _00_[55], _00_[55], _00_[55], _00_[55], _00_[55], _00_[55], _00_[55], _00_[47], _00_[47], _00_[47], _00_[47], _00_[47], _00_[47], _00_[47], _00_[39], _00_[39], _00_[39], _00_[39], _00_[39], _00_[39], _00_[39], _00_[31], _00_[31], _00_[31], _00_[31], _00_[31], _00_[31], _00_[31], _00_[23], _00_[23], _00_[23], _00_[23], _00_[23], _00_[23], _00_[23], _00_[15], _00_[15], _00_[15], _00_[15], _00_[15], _00_[15], _00_[15], _00_[7], _00_[7], _00_[7], _00_[7], _00_[7], _00_[7], _00_[7] };
  assign counter = \lfsr.lfsr_stream ;
  assign \lfsr.clk  = clk;
  assign \lfsr.lfsr  = \lfsr.lfsr_stream ;
  assign \lfsr.rst  = rst;
  assign { load[63:57], load[54:48], load[46:40], load[38:32], load[30:24], load[22:16], load[14:8], load[6:0] } = { load[56], load[56], load[56], load[56], load[56], load[56], load[56:55], load[55], load[55], load[55], load[55], load[55], load[55], load[47], load[47], load[47], load[47], load[47], load[47], load[47], load[39], load[39], load[39], load[39], load[39], load[39], load[39], load[31], load[31], load[31], load[31], load[31], load[31], load[31], load[23], load[23], load[23], load[23], load[23], load[23], load[23], load[15], load[15], load[15], load[15], load[15], load[15], load[15], load[7], load[7], load[7], load[7], load[7], load[7], load[7] };
endmodule
